### ISSUE TITLE
Handle touch events

### ISSUE THREAD

**Issue by jrpedrianes** [awslabs/diagram-maker#100]
Is possible to handle touch events? 

I'm reviewing the AWS IOT Events Dashboard from my iPad and all the gestures work properly but when I am using the demo documentation, the touch gestures don't work, ex, drag-and-drop.

**Comment by jrpedrianes** [comment]
@sameergoyal do you know how to do this?

sorry for pinging you here, I know that you non longer work at AWS but maybe you know it.

**Comment by sameer-walnut** [comment]
If you want to submit a PR, [this](https://github.com/awslabs/diagram-maker/blob/master/src/service/ui/UIEventManager.ts#L129-L137) is where we listen for all of the DOM events, we can similarly add listeners for touch events as well.

We then normalize the mouse events into our own normalized event objects for mouse click, move, etc over [here](https://github.com/awslabs/diagram-maker/blob/master/src/service/ui/UIEventNormalizer.ts#L135-L210). Similarly, we will have to normalize the touch events, preferably we can coerce them into the normalized mouse events themselves so that we dont have to make changes to other parts of diagram maker.

Doing it outside of diagram maker would require more work. Basically, you will have to add the same event listeners  and then fire diagram maker actions for node, edge, etc.

**Comment by sameergoyal** [comment]
If you want to submit a PR, you can add event listeners for touch events [here](https://github.com/awslabs/diagram-maker/blob/master/src/service/ui/UIEventManager.ts#L130-L147) alongside the other DOM events we listen to. We then convert the DOM events into a normalized event using normalizers defined [here](https://github.com/awslabs/diagram-maker/blob/master/src/service/ui/UIEventNormalizer.ts#L135-L210). You can similarly add a normalizer that converts the touch events into the normalized mouse events that diagram maker uses internally. That way changes would not be required in other places.

If you want to do this outside diagram maker, it will take more effort. You will have to attach the event listeners and then turn them into diagram maker [actions](https://github.com/awslabs/diagram-maker/blob/master/src/state/node/nodeActions.ts) for node, edge, etc.

**Comment by jrpedrianes** [comment]
thanks @sameergoyal 

I'm going to review your comment and figure out what changes we need to do.
