### ISSUE TITLE
Demo Applications Do Not Use NPM Module

### ISSUE THREAD

**Issue by moloch--** [awslabs/diagram-maker#23]
**Describe the issue with documentation**

The Demo applications do not use the NPM modules, which means it requires significant refactoring to play around with, and some code uses symbols that are not exported by the library. 

For example, the `utils.ts` code uses `LayoutType`, which is not exported by the NPM module.

<img width="1350" alt="Screen Shot 2020-11-01 at 8 42 59 AM" src="https://user-images.githubusercontent.com/875022/97805875-46f52680-1c1e-11eb-8510-d1ab06ab1832.png">

**Comment by sameergoyal** [comment]
We have made some changes to our demo application to fix this particular scenario where we were using an internal variable instead of external one that can be consumed by other applications.

In your application feel free to replace ```LayoutType``` with ```Layout``` and it should work without any other changes.

Currently, the entire application is built as a single NPM module and the demo applications are created as a testing environment to run automated tests against when we make updates to the library so its not easy to split those from the core NPM module of the library. 

Thanks for trying out the library and reporting this issue to us. Please let us know if you find any other issues or have any other feedback.
