### ISSUE TITLE
What is the preferred way to update the store data?

### ISSUE THREAD

**Issue by manevpe** [awslabs/diagram-maker#40]
**Describe the issue with documentation**
I'm tryng to dynamically update the consumerData on a particular node, after it was created.
What is the preffered way to update the store data?
It would be nice to include this in the documentation or in the examples.

**Comment by sameergoyal** [comment]
You can attach your own reducer while initializing DiagramMaker. See details on how to do this here: https://awslabs.github.io/diagram-maker/usage/initialization.html. This reducer will be invoked post invoking diagram maker's own reducer which means that if the action was initiated by diagram maker, the state changes will already be performed on the state object received by this reducer.

Furthermore, if custom actions are needed either due to user interactions with UI not controlled by Diagram Maker or due to other reasons, you can use the Dispatch API to dispatch any custom actions that will pass through Diagram Maker's own reducer without causing any state changes and can be handled appropriately within your reducer. See more details here: https://awslabs.github.io/diagram-maker/usage/api.html#dispatch.

I just checked and indeed the documentation seems to be missing this aspect. Will keep this open until we update the documentation to add this info.

**Comment by manevpe** [comment]
Thank you!
An example would be very helpful here!

I'm still a bit confused - so in order to dynamically update the consumerData, I should:
1. Add a dispatch with my own custom event
2. Add my own reducer, that will react to this custom event and mutate diagram maker's state

Is that correct?

**Comment by sameergoyal** [comment]
Yes, that is correct. 

> And would this trigger a re-render of that node, so that it can render the new data I just added in consumerData?

Yes, it should trigger a re-render of the node since the node data has changed. Please ensure that the reducer adheres to the same rules as a redux reducer, namely shallow immutability and it should trigger a re-render. See the relevant code here: https://github.com/awslabs/diagram-maker/blob/master/src/components/node/Node.tsx#L52. Also, see documentation for providing your own reducer here: https://awslabs.github.io/diagram-maker/usage/initialization.html.

**Comment by manevpe** [comment]
Thanks, this was very helpful!

I was able to get it working, except in one case - when adding a new property to consumerData, a re-render is not triggered.
Example:
My node has consumerData: {}
In my reducer, I add a new property to consumerData - { myNewProp: "Updated" }
The re-render of that node is not triggered.
If I click somewhere on the workspace, to trigger DESELECT even, the node is re-rendered and the new property is correctly visualized.

To workaround, when creating a new node or edge, on the respective renderCallbacks, I initialize all properties in consumerData with default data.

I'm not a big fan of this workaround - shouldn't the re-render be triggered when consumerData gets a new property as well?


Here is some of the code I'm using:
The dispatcher:
diagramMaker.api.dispatch({
    type: "CONSUMER_DATA_CHANGED",
    payload: {
        nodeId: myNodeId,
        consumerData: data
    }
});

The reducer:
new DiagramMaker(
    ...
    actionInterceptor: (action, dispatch, getState) => {
        ...
        // MY CUSTOM EVENTS
        if (action.type === "CONSUMER_DATA_CHANGED") {
            myConsumerDataReducer(getState(), action.payload);
        }
    },
    {
        consumerEnhancer: addDevTools(),
        initialData: graphData,
        consumerRootReducer: myConsumerDataReducer
    }
);

const myConsumerDataReducer = (state, data) => {
    Object.assign(state.nodes[data.nodeId].consumerData, data.consumerData);
    return state;
};

**Comment by sameergoyal** [comment]
I see 2 issues with above code:

1. There should be no need to use ActionInterceptor for this use case. The ActionInterceptor is useful for modifying, cancelling or triggering additional actions. It should not be used for any modification of state directly. Modification of state is handled by reducers and as long as you pass the myConsumerDataReducer into consumerRootReducer attribute of the initialization params, it is then Diagram Maker's responsibility to invoke the reducer for every single action on the store. See action interceptor documentation here: https://awslabs.github.io/diagram-maker/usage/configuration.html#action-interceptor.

2. In your reducer, you seem to be updating state directly using Object.assign and update the same object and returning it rather than creating a new object. This violates shallow immutability. We do not use deep equality checks to check for changes in data hence new objects need to be created whenever data is changing. It might require a lot of discipline to keep enforcing so DiagramMaker internally uses immer where we can use mutative code and still have immer create new objects. See an example here: https://github.com/awslabs/diagram-maker/blob/master/src/state/node/nodeReducer.ts#L41. Furthermore, in the newer redux toolkit, the [createReducer](https://redux-toolkit.js.org/api/createReducer) method also uses immer underneath so using [immer](https://immerjs.github.io/immer/) might be a good idea for your reducers.

You can read more about how redux separates state updates into actions (data/metadata required for state update) and reducers (logic to compute new state based on previous state & action data) here: https://redux.js.org/introduction/core-concepts.

**Comment by manevpe** [comment]
Both of these make sense.

I've updated my code accordingly and I can confirm that the re-render works correctly, even if the consumerData was not defined.

Thanks for all the help!

**Comment by sameergoyal** [comment]
Sure, we'll keep this open until we update the documentation with an example for this.

**Comment by tracfren** [comment]
Sorry, we are not planning to act on this request in any timely manner and will be closing this issue. Thank you.
