### ISSUE TITLE
Scrollbars and mouse wheel scroll instead of zoom

### ISSUE THREAD

**Issue by manevpe** [awslabs/diagram-maker#42]
**Is your feature request related to a problem? Please describe.**
I'd like to have scrollbars that I can use. It would help me with visual orientation on the workspace.
I'd like to be able to scroll with the mouse wheel, instead of zooming in / out.

**Describe the solution you'd like**
A configuration option to enable scrollbars.
A configuration option to set the behaviour of the mouse wheel.

**Describe alternatives you've considered**
I tried setting the css "overflow: scroll" on the "dm-view" element, so that I get the scrollbars.
I tried intercepting the WORKSPACE_ZOOM action, stopping it, and instead dispatching a custom action to scroll.
This custom action is updating the scrollTop property of the "dm-view" element, in order to scroll up and down.
This works, but does not feel very natural. Also, I need to handle panning in a similar way.
I think there should be a way to natively see and use scrollbars and to be able to configure the mouse wheel action.

**Comment by sameergoyal** [comment]
That is currently not possible and the approach you mentioned of intercepting the zoom action and instead dispatching a different action is the only way. One slight improvement you can make is instead of dispatching the custom action, you can dispatch a "WORKSPACE_DRAG" action that is used internally to pan the workspace. Here is the interface for that action: https://github.com/awslabs/diagram-maker/blob/master/src/state/workspace/workspaceActions.ts#L37-L43.

However, a new feature will have to added to provide this as a configuration option. Would you be willing to submit a PR for this feature?

**Comment by manevpe** [comment]
I could work on this when I get some free time.
I would however need some guidance on the architecture setup and the configuration option.

**Comment by manevpe** [comment]
I created a draft PR.
I could use some guidance on couple of things:
1. How to access the current config in the workspace reducer?
2. How to handle changing the container scrollTop / scrollLeft properties on zoom / pan actions?

**Comment by sameergoyal** [comment]
Apologies for the really late response. I have reviewed the PR and provided some guidance.

**Comment by tracfren** [comment]
Sorry, we are not planning to act on this request in any timely manner and will be closing this issue. Thank you.
