### ISSUE TITLE
Pass original input event attributes with dispatched actions

### ISSUE THREAD

**Issue by manevpe** [awslabs/diagram-maker#43]
**Is your feature request related to a problem? Please describe.**
In my action interceptors, for mouse / keyboard type of events, I'd like to receive the information about the original event that triggered the action - ex. left click or mouse wheel.
This would allow me to get more information about the event, based on which I could make a decision - ex. if Ctrl key was held while selecting a node, add to the selection, instead of selecting only this node.

**Describe the solution you'd like**
For events that originated from mouse / keyboard input type of events, automatically pass the original event data in the payload of the action, similar to how it is done in the event listeners.

**Describe alternatives you've considered**
I considered stopping the native action in an action interceptor, and then using an event listener for input events, and passing my custom events with the original event data along side, but that is too messy and requires to overwrite a lot of the native action events.

**Comment by sameergoyal** [comment]
Diagram Maker's flow is as follows: [UI events -> Actions -> New state -> Updated UI](https://awslabs.github.io/diagram-maker/usage/architecture.html). The transformation of UI events to actions is done inside a specific UI event listener built inside of Diagram Maker. The actions carry only the relevant information to influence the creation of next state update.

The way this use case can be built with existing customization options is by using the [eventListener](https://awslabs.github.io/diagram-maker/usage/initialization.html). If you pass an eventListener into DiagramMaker, it is invoked with DiagramMaker's [normalized UI events](https://github.com/awslabs/diagram-maker/blob/master/src/service/ui/UIEventNormalizer.ts#L60-L67) that also have the original UI event. You can listen to these UI events and dispatch custom actions using the dispatch API of DiagramMaker. You will still have to use actionInterceptor to cancel the action in case DiagramMaker generates one for the same UI event.

Note: We need to update the architecture diagram over here: https://awslabs.github.io/diagram-maker/usage/architecture.html to show the additional hook i.e. eventListener that is provided to consumers of this library.

**Comment by manevpe** [comment]
I considered this approach, but what I don't like about it, is that it is intercepting too much of the "native" logic.
What I'd like is in the actionInterceptor, to be able to check whether Ctrl key was held when an action was done, and only then intercept the default action.
For example - if selecting a node with Ctrl - add to the current selection, instead of replacing it.

This can certainly be achieved today, but it requires too much mendling:
 - intercepting and stopping the default action
 - creating a default event listener
 - sending a new action event
 - creating a new action handler that would perform custom action or re-implement the default action

It would be much simpler, if the original input event data was carried over and send as part of the action event.

**Comment by sameergoyal** [comment]
Thinking more on this. 

1. Actions can only contain serializable objects and browser native events contain functions so attaching the full event on the action might not be possible. Furthermore, if we do want to consider attaching some trimmed down information about the original UI event on the action, we will have to review it as a change in DiagramMaker's architecture since the architecture for Diagram Maker relies on conversion of UI events into actions at the event listener level.

2. Furthermore, DiagramMaker was built with the idea of making all the most common interactions available out of the box. Furthermore, for common interactions that are mutually exclusive with other interactions (dragging to pan, dragging to draw a selection box) as modes, so once again, consumers choose a mode and get the behavior they want from DiagramMaker out of the box without having to write a lot of custom logic. The use case you mention seems common enough to build this functionality natively so that the default behavior in the Drag mode is that click on node replaces selection, and click along with Ctrl (on windows) or Cmd (on Mac) adds to selection out of the box in Diagram Maker.

3. Even though it is intercepting too much of the native logic, we want to continue to provide this functionality for very custom interactions for a specific use case that will not extend to all consumers of DiagramMaker. Some of our consumers who have very specialized use cases can use those hooks to customize DiagramMaker to their needs, but in this particular case I do agree it is too much lift for an interaction that is very common.

Would you be willing to submit a PR for adding this functionality?

**Comment by manevpe** [comment]
I could work on this when I get some free time.
I would however need some guidance on the architectural setup and what would be the best approach - to pass the event as a property of the action, or something else...

**Comment by manevpe** [comment]
I've made a PR with a possible solution for this.
Currently, it only handles the mouse wheel events.
I wanted to verify with you, that this is the correct approach, before handling all events.
@sameergoyal Let me know, what you think.

**Comment by sameergoyal** [comment]
Apologies for the really long wait @manevpe. I have taken a look at the PR and will be providing feedback on the PR directly, but it seems I got misunderstood. 

I was not recommending a PR to pass the originalEvent into the action. I was suggestion updating our code base such that for node click actions, additional boolean flag is added for the "modifier" key. Then using the "boolean" flag inside the reducer to append to the selection, rather than replacing the selection.

This would achieve the complete use case you were looking here without passing the originalEvent into the action. This would also enable other consumers of this library to rely on the "modifier" key flag and not have to implement OS specific logic to differentiate between Ctrl on windows vs Cmd on Mac.

**Comment by tracfren** [comment]
Sorry, we are not planning to act on this request in any timely manner and will be closing this issue. Thank you.
