### ISSUE TITLE
Diagram Maker cannot handle large number of nodes in canvas.

### ISSUE THREAD

**Issue by rahul-codeb** [awslabs/diagram-maker#68]
I'm trying to replace the background diagram-maker canvas svg, with custom small circular nodes. So, probably this lead to more than 5000 number of circular nodes.

This is causing Performance Issues. Any suggestions, how to optimize this usecase?

**Comment by occhangg** [comment]
Apologies for the delay in our response and thank you for reaching out. 

What is the reason that you are adding small circular nodes?

**Comment by notsonoobiee** [comment]
I wanted to implement circular node to the canvas (instead of the svg currently provided with diagram-maker) to make the dots respond to other Main Nodes.

I'm able to achive this, but with a cost of performance. The Number of nodes for creating canvas dots was about 5000, which lead to performance issues.

Expectations:
![image](https://user-images.githubusercontent.com/89071284/129900492-19ba8b80-e58a-4049-8370-726a83784676.png)

Please let me know, how can we achive this in diagram-maker without loosing performance.

Thanks.

**Comment by occhangg** [comment]
Could you provide us a simple code so we can take a deeper look into this problem that you are facing?

**Comment by tracfren** [comment]
Sorry, we are not planning to act on this request in any timely manner and will be closing this issue. Thank you.
