### ISSUE TITLE
Expose event filter to be customized

### ISSUE THREAD

**Issue by richardaum** [awslabs/diagram-maker#83]
**Is your feature request related to a problem? Please describe.**
There are only a few options for editor mode: READ_ONLY, SELECT and DRAG. With only those options, it isn't possible to make a node selectable but not draggable.

**Describe the solution you'd like**
Instead of creating new editor mode types, exposing a way to provide a custom event filter would be very useful:

```typescript
new DiagramMaker(..., {
  eventFilter(e: NormalizedEvent, editorMode: EditorModeType, rootEventFilter: EventFilter): boolean {
    if (e.type === MouseClickEventType.LEFT_CLICK) return true;
    return rootEventFilter(e, editorMode);
  }
);
```

**Describe alternatives you've considered**
I've tried to use all those editor modes available, but none of those behave as desired.

**Additional context**
N/A

**Comment by sameergoyal** [comment]
Diagram Maker provides several hooks to be able to implement custom functionality such as making a node selectable but not draggable. For example, one way would be to use [action interceptor](https://awslabs.github.io/diagram-maker/usage/configuration.html#action-interceptor) & cancel any node drag actions. This would also be the simplest since you wont need to deal with individual UI events such as mousedown, mousemove, mouseup, etc.

However, if you do wish to listen to all events flowing through diagram maker, you can pass your own [event listener](https://awslabs.github.io/diagram-maker/usage/initialization.html). Some examples for event listener can be found under the [plugin documentation](https://awslabs.github.io/diagram-maker/plugins/interaction.html) since we believe that plugins might be the primary consumer of this functionality and direct consumers might find it more friendly to deal with action interceptors instead.

Let us know if you are able to achieve the desired behavior with the one of the above options.

**Comment by richardaum** [comment]
I've tried both of them. I like how we can use action interceptor to prevent Redux actions to be executed. I'm going with that. Thank you!
